### ISSUE TITLE
Parse string with multiple nodes

### ISSUE THREAD

**Issue by paulocheque** [bitinn/vdom-parser#14]
I tried the following command: `parser('<h1>aaa</h1><h2>bbb</h2>')`

But it returns only the `h1` node. Always the first. How can I parse a string to return all nodes recursively?

I was expecting some result like:  `[h1, h2]`

**Comment by bitinn** [comment]
For string parsing we intend to stay simple and consistent, if you look at the source, we only parse the first element and its children. This is consistent with what you would do when using DOM (there is only one vdom to diff and patch)

However it shouldn't be too hard to write a helper function that split tags and feed them into `vdom-parser`if you wish to do that.

ref: https://github.com/bitinn/vdom-parser/blob/master/index.js#L39-L51

**Comment by paulocheque** [comment]
Oh, cool! Thanks!

Or I can create a parent node to attach all nodes as children.

Thanks, I will try it!
