### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by agentcooper** [bitinn/vdom-parser#8]
For animations in virtual-dom we need to use hooks [1]. Can we think of the way to specify them in html structure?

Something like

``` js
var state = { items: ['a', 'b', 'c'] };

// https://github.com/Matt-Esch/virtual-dom/blob/master/docs/css-animations.md
var hooks = { insertedClassName: ItemInsertHook };

var renderItem = (item) => {
  return '<li class="item" data-hook-inserted-classname="item--inserted"></li>';
}

var render = (state) => {
  return '<ul>' + state.items.map(renderItem)  + '</ul>';
}

parser(render(state), {}, hooks);
```

Is there a better solution? Maybe providing some ref to the vdom element?
- [1] https://github.com/Matt-Esch/virtual-dom/blob/master/docs/css-animations.md

**Comment by bitinn** [comment]
I hope there is no confusion: you should only use `vdom-parser` to parse server-rendered html, it will create a vdom so that you can diff/patch against your client-side rendered vdom, using `virtual-dom` api.

If you use hooks, after diff/patch your hook will be rendered as usual.

**Comment by agentcooper** [comment]
I currently use vdom as an additional step after the custom string-based templating engine (e.g Mustache). So the initial source of truth is not vdom, but html-like text.

**Comment by bitinn** [comment]
My question: if I disable javascript and visit your site, do I get a rendered page or a blank page. If answer is former, then give document.body to `vdom-parser` and use it's result.

If latter, what do you use `vdom-parser` for?

**Comment by agentcooper** [comment]
I use custom templates, which are implemented for perl and javascript, so page template is shared between backend and frontend and initial page render is done with backend, no javascript required. Because there is lots of dynamic stuff on the page after the initial load, I use `vdom-parser` to make rerender simple and predictable.

**Comment by bitinn** [comment]
How do you re-render without `virtual-dom` ?

**Comment by agentcooper** [comment]
Think of the following:

``` html
<script type="text/template" id="tmpl">
<div>
    <ul>
        {{#fruits}}
            <li class="fruit {{#active}}fruit--active{{/active}}">
                {{name}}
            </li>
        {{/fruits}}
    </ul>
    <button class="btn">Add item</button>
</div>
</script>
```

``` js
var hogan = require('hogan.js');

var mainLoop = require('main-loop');

var parser = require('vdom-parser');

var initState = {
    fruits: [{ name: 'apple'}, { name: 'banana', active: true}]
};

function tmpl(string, data) {
    var template = hogan.compile(string);
    var output = template.render(data);

    return parser(output);
}

function render(state) {
    return tmpl(document.querySelector('#tmpl').innerHTML, state);
}

var loop = mainLoop(initState, render, {
    create: require('virtual-dom/create-element'),
    diff: require('virtual-dom/diff'),
    patch: require('virtual-dom/patch')
});

document.body.appendChild(loop.target);

document.querySelector('.btn').addEventListener('click', function(event) {
    initState.fruits.push({ name: 'fruit' + Math.random() });
    loop.update(initState);
});
```

**Comment by bitinn** [comment]
Sorry `vdom-parser` is not designed for this use-case, you won't get the same feature set as writing virtual-hyperscript (`h`).

**Comment by agentcooper** [comment]
Ok, I understand, my thought was that hooks can also fit here since there is already a mechanism to provide key lookup (`attr` parameter).
